# Generated by Django 4.0.3 on 2022-05-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('siteurl', models.CharField(max_length=255)),
                ('shortdis', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
