# Generated by Django 4.0.3 on 2022-05-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boredbuttonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('siteurl', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='gameimage')),
            ],
        ),
    ]
