# Generated by Django 4.0.3 on 2022-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boredbuttonapp', '0003_alter_games_siteurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='siteurl',
            field=models.CharField(max_length=255),
        ),
    ]
